FROM python:3.12-slim

# Evita archivos .pyc y buffer
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Instalar dbt + duckdb + git
RUN apt-get update && apt-get install -y git \
    && pip install --no-cache-dir dbt-duckdb==1.8.0

WORKDIR /usr/app

CMD ["tail", "-f", "/dev/null"]
